substitutions:
  node_platform: ESP8266
  node_board: esp01_1m

packages:
  device_base: !include ../common/base.yaml
#  basic_sensors: !include ../common/basic_sensors.yaml

# Enable MQTT and support master on/off switch
#mqtt:
#  broker: 192.168.50.18
#  on_message:
#    - topic: "shelly_uni_/binary_sensor/switch_1_shelly_uni_13/state"
#      then:
#        - light.turn_off: device_light

output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_r

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_b

  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_w

light:
  - platform: rgbw
    name: ${light_name}
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
    effects:
      - random:
      - strobe:
      - flicker:
    id: device_light

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: ${switch_name}
    on_state:
      then:
        - light.toggle: device_light
    internal: true
    id: device_switch
