substitutions:
  node_name: d5-8-4chan-living
  friendly_name: 4 channel switch living
  switch1: D8 Master Switch
  switch2: D5 Door Light
  switch3: D6 Scare Light
  switch4: D7 Floor Light

packages:
  device_base: !include devices/mic-4ch.yaml

mqtt:
  on_message:
    - topic: d5-8-4chan-living/light/d7_floor_light/remote
      then:
        - light.toggle: light4
 
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button1
    on_press:
      then:
        switch.toggle: switch1
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button2
    on_press:
      - light.toggle: light2

  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    id: button3
    on_press:
      - light.toggle: light3

  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button4
    on_press:
      - light.toggle: light4
   
switch:
  - platform: template
    name: ${switch1}
    id: switch1
    optimistic: true

light:
  - platform: binary
    name: ${switch2}
    id: light2
    output: relay2

  - platform: binary
    name: ${switch3}
    id: light3
    output: relay3

  - platform: binary
    name: ${switch4}
    id: light4
    output: relay4

