substitutions:
  node_name: f1-4ch-bedroom
  friendly_name: bedroom light
  light_name: bedroom light
  switch_name: bedroom Switch

packages:
  device_base: !include devices/shelly-rgbw2.yaml

# Light can be turned off by Living Room Master Switch
mqtt:
  on_message:
    - topic: "d5-8-4chan-living/switch/master_switch/state"
      then:
        - light.turn_off: device_light

# This device is connected to 4 LED lights
light:
  - platform: monochromatic
    name: ${light_name}
    output: pwm_w
    id: device_light

# Short press on momentary switch toggles light
# Pressing and holding will dim the light
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: ${switch_name}
    internal: true
    id: device_switch
    on_click:
      then:
        - if:
            condition:
              - light.is_off: device_light
            then:
              - light.turn_on:
                  id: device_light
                  brightness: 1.0
            else:
              - light.turn_off: device_light
 
    on_press:
      then:
        - if:
            condition:
              light.is_off: device_light
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: device_switch
                  then:
                    - light.dim_relative:
                        id: device_light
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: device_switch
                      - light.is_on: device_light
                  then:
                    - light.dim_relative:
                        id: device_light
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
