substitutions:
  node_name: g1-bedroom-sensor 
  friendly_name: Bedroom Sensor 

packages:
  device_base: !include devices/atom-lite.yaml

sensor:
  - platform: scd4x
    co2:
      name: "Bedroom CO2"
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
