substitutions:
  node_name: g2-living-room-sensor 
  friendly_name: Living Room Sensor 

packages:
  device_base: !include devices/atom-lite.yaml

sensor:
  - platform: scd4x
    co2:
      name: "Living Room CO2"
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
