substitutions:
  node_name: g7-tpms-gateway 
  friendly_name: TPMS Gateway 

packages:
  device_base: !include devices/atom-lite.yaml

esphome:
  includes:
    - devices/tpms.h

text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: tpms_update
    on_value:
      then:
        - mqtt.publish:
            topic: some/topic
            payload: id(tpms_update).state
button:
  - platform: template
    id: tpms_init
    name: "TPMS initialization"
    on_press:
      then:
        - uart.write: !lambda |-
            unsigned char data[] = {
              0x02,                           // STX
              0x72,0x00,                      // Length
              0x80,0x20,0x00,                 // Command = Set Configuration Ref Plus (V2.02)
              
              // Tire Number 1 (Driver Front Left)
              0x11,                           // Position
              0x6F,0xC8,0x2B,                 // Serial Number
              0x46,                           // Reference Pressure = 70 PSI
              
              // Tire Number 2 (Passenger Front Right)
              0x12,                           // Position
              0x96,0xD5,0x2B,                 // Serial Number
              0x46,                           // Reference Pressure = 70 PSI
          
              // Tire Number 3 (Dualies Left Outer)
              0x21,                           // Position
              0x80,0xCA,0x2B,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 4 (Dualies Left Inner)
              0x22,                           // Position
              0x80,0xCA,0x2B,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 5 (Dualies Right Inner)
              0x23,                           // Position
              0x80,0xCA,0x2B,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 6 (Dualies Right Outer)
              0x24,                           // Position
              0x80,0xCA,0x2B,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 7 (Tag Axle Left)
              0x31,                           // Position
              0xAD,0xD5,0x2B,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 8 (Tag Axle Right)
              0x32,                           // Position
              0xAD,0xD5,0x2B,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 9 (Spare)
              0x41,                           // Position
              0x3C,0xC8,0x2B,                 // Serial Number
              0x32,                           // Reference Pressure = 50 PSI
              
              
              // Tires Number 10 through 16 (Not Used)
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 10
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 11
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 12
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 13
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 14
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 15
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 16
              
              0x0F,                           // Timeout = 15
              0x12,                           // Over Percentage = 128%
              0x90,                           // Under Percentage = 74%
              0x5D,                           // Maximum Temperature = 93ºC
              
              0xEF,                           // MID Flags
              0x00,                           // Delta Pressure = Off  
              
              0x42,0x65,0x61,0x73,0x74,0x69,0x65,0x00,    // Unit name is "Beastie"
              
              0x00,0xFF,0xFF,                 // TPMS structure2, Cross Axle, Tire Layout h and l
              
              0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,  // Spare1 through Spare6
              
              0x01,                           // Timers
              0x01,                           // Forces an Alarm 
              
              0xFF,0xFF,                      // Spare7 and Spare8
          
              0xFF,                           // Sys Flags 
              
              0xFF,0xFF,0xFF,                 // Spare9 through Spare11
              
              0x00,                           // Checksum, will be calculated.
              0x03                            // ETX
              };
    
            // Calculate Checksum
            int i = 0;
            int sum = 0;
            
            for (i = 1; i < sizeof(data)/sizeof(data[0])- 2 ; i++) {
                sum += data[i];
            }
            
            data[sizeof(data)/sizeof(data[0])-2] = sum % 256;
            return std::vector<unsigned char>(std::begin(data), std::end(data));

