substitutions:
  node_name: g7-tpms-gateway 
  friendly_name: TPMS Gateway 

# https://docs.m5stack.com/en/atom/atomic232
uart:
  tx_pin: 19
  rx_pin: 22
  baud_rate: 9600
  id: uart_bus
  debug:
    direction: BOTH
    after:
      delimiter: "0x03"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

packages:
  device_base: !include devices/atom-lite.yaml

esphome:
  includes:
    - devices/tpms.h

text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: tpms_update
    on_value:
      then:
        - mqtt.publish:
            topic: pressurepro/tpms/status
            payload: !lambda |-
              return id(tpms_update).state;
button:
  - platform: template
    id: tpms_version
    name: "TPMS version"
    on_press:
      then:
        - uart.write: !lambda |-
            unsigned char data[] = {
              0x02,0x01,0x00,0x44,0x45,0x03
            };
            return std::vector<unsigned char>(std::begin(data), std::end(data));
  
  - platform: template
    id: tpms_init
    name: "TPMS initialization"
    on_press:
      then:
        - uart.write: !lambda |-
            unsigned char data[] = {
              0x02,                           // STX
              0x72,0x00,                      // Length
              0x80,0x20,0x00,                 // Command = Set Configuration Ref Plus (V2.02)
              
              // Tire Number 1 (Driver Front Left)
              0x11,                           // Position
              0xBA, 0x9D, 0x86,                 // Serial Number
              0x46,                           // Reference Pressure = 70 PSI
              
              // Tire Number 2 (Passenger Front Right)
              0x14,                           // Position
              0xB2, 0x1D, 0x62,                 // Serial Number
              0x46,                           // Reference Pressure = 70 PSI
          
              // Tire Number 3 (Dualies Left Outer)
              0x21,                           // Position
              0xAF, 0x9D, 0x86,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 4 (Dualies Left Inner)
              0x22,                           // Position
              0x3F, 0x5A, 0x74,                // Serial Number (new)
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 5 (Dualies Right Inner)
              0x23,                           // Position
              0x6F, 0xB5, 0x86,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 6 (Dualies Right Outer)
              0x24,                           // Position
              0xBF, 0x1D, 0x62,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 7 (Tag Axle Left)
              0x31,                           // Position
              0x64, 0xB5, 0x86,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 8 (Tag Axle Right)
              0x34,                           // Position
              0x78, 0x1D, 0x62,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI
              
              // Tire Number 9 (Spare)
              0x41,                           // Position
              0x7A, 0x1D, 0x62,                 // Serial Number
              0x32,                           // Reference Pressure = 50 PSI
              
              // Airbag Number 1 (Driver front Left)
              0x51,                           // Position
              0xC7, 0x04, 0xC3,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI

              // Airbag Number 2 (Passenger front Right)
              0x52,                           // Position
              0x7B, 0x94, 0x78,                 // Serial Number
              0x3C,                           // Reference Pressure = 60 PSI

              // Airbag Number 3 (Back - System Pressure)
              0x53,                           // Position
              0x21, 0x03, 0xC3,                 // Serial Number
              0x50,                           // Reference Pressure = 80 PSI

              // Airbag Number 4 (Back - Airbags Pressure)
              0x54,                           // Position
              0x61, 0xC9, 0x8C,                 // Serial Number
              0x50,                           // Reference Pressure = 80 PSI

              // Tires Number 14 through 16 (Not Used)
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 14
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 15
              0xFF,0x00,0x00,0x00,0xFF,       // Tire 16
              
              0x0F,                           // Timeout = 15
              0x12,                           // Over Percentage = 128%
              0x90,                           // Under Percentage = 74%
              0x5D,                           // Maximum Temperature = 93ºC
              
              0xEF,                           // MID Flags
              0x00,                           // Delta Pressure = Off  
              
              0x42,0x65,0x61,0x73,0x74,0x69,0x65,0x00,    // Unit name is "Beastie"
              
              0x00,0xFF,0xFF,                 // TPMS structure2, Cross Axle, Tire Layout h and l
              
              0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,  // Spare1 through Spare6
              
              0x01,                           // Timers
              0x01,                           // Forces an Alarm 
              
              0xFF,0xFF,                      // Spare7 and Spare8
          
              0xFF,                           // Sys Flags 
              
              0xFF,0xFF,0xFF,                 // Spare9 through Spare11
              
              0x00,                           // Checksum, will be calculated.
              0x03                            // ETX
              };
    
            // Calculate Checksum
            int i = 0;
            int sum = 0;
            
            for (i = 1; i < sizeof(data)/sizeof(data[0])- 2 ; i++) {
                sum += data[i];
            }
            
            data[sizeof(data)/sizeof(data[0])-2] = sum % 256;
            return std::vector<unsigned char>(std::begin(data), std::end(data));

