# issue to be solved: upon boot relay 1 and 2 ore on, but audio switch is off. both are therefore out of sync.

substitutions:
  node_name: h1-4-overhead-control
  friendly_name: 4 channel switch 

packages:
  device_base: !include devices/nodemcu.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: D0
      mode:
        input: true
      inverted: true
    id: button1
    on_press: 
      then:
        - lambda: |-
            if (id(switch1).state) {
              id(switch1).publish_state(false);
              id(relay1).turn_off();
              id(relay2).turn_off();
            } else {
              id(switch1).publish_state(true);
              id(relay1).turn_on();
              id(relay2).turn_on();
            }
  - platform: gpio
    pin:
      number: D1
      mode:
        input: true
        pullup: true
      inverted: true
    id: button2
    on_press:
      - switch.toggle: switch3

  - platform: gpio
    pin:
      number: D2
      mode:
        input: true
        pullup: true
      inverted: true
    id: button3
    on_press:
      - switch.toggle: switch4

  - platform: gpio
    pin:
      number: D5
      mode:
        input: true
        pullup: true
      inverted: true
    id: button4

switch:
  - platform: template
    name: Switch Audio
    id: switch1
    optimistic: true
    turn_on_action:
      - output.turn_on: relay1
      - output.turn_on: relay2
    turn_off_action:
      - output.turn_off: relay1
      - output.turn_off: relay2

  - platform: template
    name: Beastie Switch Overhead
    id: switch2
    optimistic: true

  - platform: template
    name: TV Switch
    id: switch3
    optimistic: true

  - platform: template
    name: Storage Switch
    id: switch4
    optimistic: true

output:
  - platform: gpio
    pin: D7
    id: relay1

  - platform: gpio
    pin: D6
    id: relay2
