substitutions:
  node_name: h2-4-4chan-overhead
  friendly_name: 4 channel switch 
  switch1: H2 Audio Left
  switch2: H2 Audio Right`
  switch3: H3 TV Switch
  switch4: H4 Beastie Overhead Switch

packages:
  device_base: !include devices/mic-4ch.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button1
    on_press:
      then:
        - switch.toggle: switch1
        - switch.toggle: switch2

  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button2
    on_press:
      - switch.toggle: switch3

  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    id: button3
    on_press:
      - switch.toggle: switch4

  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button4
   
switch:
  - platform: output
    name: ${switch1}
    id: switch1
    output: relay1

  - platform: output
    name: ${switch2}
    id: switch2
    output: relay2

  - platform: output
    name: ${switch3}
    id: switch3
    output: relay3

  - platform: output
    name: ${switch4}
    id: switch4
    output: relay4
