# Source: https://www.esphome-devices.com/devices/Shelly-Plus-1

substitutions:
  node_platform: esp32
  node_board: esp32doit-devkit-v1
  max_temp: "70.0"

packages:
#  device_base: !include ../common/base.yaml
  basic_sensors: !include ../common/basic_sensors.yaml

esphome:
  name: ${node_name}
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: ${node_board}
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

ota:

logger:

wifi:
  ssid: !secret WIFI_SSID
  password: !secret  WIFI_PASSWORD
#  use_address: 4-chan-living.local

  # Enable fallback hotspot (captive portal) in case WiFi connection fails
#ap:
#    ssid: ${friendly_name} 
#    password: !secret AP_PASSWORD

# captive portal not supported with esp-idf framework
# captive_portal:

mqtt:
  broker: !secret MQTT_HOST
  username: !secret MQTT_USER
  password: !secret MQTT_PASSWORD

output:
  - platform: gpio
    id: relay_output
    pin: GPIO26

switch:
  - platform: output
    id: relay
    name: "${friendly_name} Relay"
    output: relay_output

binary_sensor:
  - platform: gpio
    name: "${switch_name}"
    pin: GPIO4
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 50ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${friendly_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: "relay"
          - mqtt.publish:
              topic: ${node_name}/overheat
              payload: "${friendly_name} has overheated"

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 6kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 11db

  - platform: adc
    name: "${friendly_name} Relay Supply Voltage"
    pin: GPIO33
    attenuation: 11db
    filters:
      - multiply: 8

status_led:
  pin:
    number: GPIO0
    inverted: true

