# Basic config from: https://www.esphome-devices.com/devices/Shelly-1 

substitutions:
  node_platform: ESP8266
  node_board: esp01_1m

packages:
  device_base: !include ../common/base.yaml
  basic_sensors: !include ../common/basic_sensors.yaml

# All Shelly 1 devices are turned off by master switch
#mqtt:
#  on_message:
#    - topic: "test-master-switch/switch/master_switch/state"
#      then:
#        - light.turn_off: device_light

output:
  - platform: gpio
    pin: GPIO4
    id: device_relay_1
