# Basic config from: https://www.esphome-devices.com/devices/Shelly-25#configuration-as-relay-with-overpower-and-overtemperature-protection 

substitutions:
  node_platform: ESP8266
  node_board: esp01_1m
  max_temp: "90.0"
  max_power: "1000"

packages:
  device_base: !include ../common/base.yaml
  basic_sensors: !include ../common/basic_sensors.yaml

i2c:
  sda: GPIO12
  scl: GPIO14

switch:
  - platform: gpio
    pin: GPIO15
    id: device_relay_2
    name: "${friendly_name} relay 2"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: GPIO4
    id: device_relay_1
    name: "${friendly_name} relay 1"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
    filters:
      - delayed_on_off: 50ms # small delay to prevent debouncing
    name: "${switch_name_1}"
    on_press:
      then:
        - switch.toggle: device_relay_1
    internal: true
    id: device_switch_1 
  - platform: gpio
    pin:
      number: GPIO5
    filters:
      - delayed_on_off: 50ms # small delay to prevent debouncing
    name: "${switch_name_2}"
    on_press:
      then:
        - switch.toggle: device_relay_2
    internal: true
    id: device_switch_2 

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${friendly_name} temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: device_relay_1
          - switch.turn_off: device_relay_2
          - mqtt.publish:
              topic: ${node_name}/overheat
              payload: "${friendly_name} has overheated. Relays turned off"
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

  - platform: ade7953_i2c
    irq_pin: GPIO16 # Prevent overheating by setting this
    voltage:
      name: ${friendly_name} voltage
    # On the Shelly 2.5 channels are mixed ch1=B ch2=A
    current_a:
      name: ${friendly_name} current 2
      internal: true
    current_b:
      name: ${friendly_name} current 1
      internal: true
    active_power_a:
      name: ${friendly_name} power 2
      id: power_channel_2
      # active_power_a is normal, so don't multiply by -1
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: device_relay_2
            - mqtt.publish:
                topic: ${node_name}/overpower
                payload: "${friendly_name} has exceeded max power. Relays 2 turned off"
    active_power_b:
      name: ${friendly_name} power 1
      id: power_channel_1
      # active_power_b is inverted, so multiply by -1
      filters:
        - multiply: -1
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: device_relay_1
            - mqtt.publish:
                topic: ${node_name}/overpower
                payload: "${friendly_name} has exceeded max power. Relays 1 turned off"
    update_interval: 30s
