# Base config that is shared across all devices
esphome:
  name: ${node_name}
  platform: ${node_platform}
  board: ${node_board}
  build_path: ./build/${node_name}

logger:

ota:

wifi:
  ssid: !secret WIFI_SSID
  password: !secret  WIFI_PASSWORD
  # use_address: shelly_uni_.local

  # Enable fallback hotspot (captive portal) in case WiFi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret AP_PASSWORD

captive_portal:

mqtt:
  broker: 192.168.50.18
